Add category slug (#192)
* PR test

* wip

* Add migrations for category slugs

* Add logic in forms.py to circumvent error when CI runs

Fixes error:
django.db.utils.ProgrammingError: relation "blog_category" does not exist

* Adjust view to accomodate new slug field

* Experiment

* Suppress user input in CI migrations

* wip

* Change 'category' to 'slug' in all instances

* remove hardcodded user directories

---------

Co-authored-by: John Solly <jsolly@umd.edu>